import {
  Creator,
  Restaurant,
  Content,
  Dish,
  ContentWithRelations,
  CuisineType,
  VibeTag,
  PriceRange,
  SponsorshipStatus,
  ContentType,
} from '@/types';

// SEED CREATORS
export const SEED_CREATORS: Creator[] = [
  {
    id: 'creator-1',
    display_name: 'Hungry Hotline',
    slug: 'hungry-hotline',
    instagram_handle: '@hungryhotline',
    tiktok_handle: '@hungryhotline',
    instagram_followers: 87000,
    tiktok_followers: 124000,
    bio: 'Pizza lover & restaurant explorer. Finding the best bites in Phoenix metro. DMs for collabs.',
    avatar_url: '/creators/avatar-1.jpg',
    tier: 'gold',
    specialties: ['Italian', 'American'],
    areas_covered: ['Downtown Phoenix', 'Scottsdale', 'Tempe', 'Chandler'],
    rate_range_low: 1500,
    rate_range_high: 3000,
    is_founding_creator: true,
    is_active: true,
    platform_fee_rate: 0.15,
    content_rights_status: 'full_rights',
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 'creator-2',
    display_name: 'Tastes of AZ',
    slug: 'tastes-of-az',
    instagram_handle: '@tastesofaz',
    tiktok_handle: '@tastesofaz',
    instagram_followers: 156000,
    tiktok_followers: 203000,
    bio: 'Arizona food & culture. Local eats, hidden gems, chef interviews. Passionate about community.',
    avatar_url: '/creators/avatar-2.jpg',
    tier: 'platinum',
    specialties: ['Mexican', 'American', 'Thai', 'Japanese'],
    areas_covered: ['Phoenix', 'Scottsdale', 'Tempe', 'Mesa', 'Chandler', 'Gilbert'],
    rate_range_low: 2000,
    rate_range_high: 5000,
    is_founding_creator: true,
    is_active: true,
    platform_fee_rate: 0.12,
    content_rights_status: 'full_rights',
    created_at: '2024-01-15T08:30:00Z',
  },
  {
    id: 'creator-3',
    display_name: 'AZ Food Guy',
    slug: 'az-food-guy',
    instagram_handle: '@azfoodguy',
    tiktok_handle: '@azfoodguy',
    instagram_followers: 62000,
    tiktok_followers: 89000,
    bio: 'Honest food reviews. No filter, no BS. Just trying everything in Phoenix.',
    avatar_url: '/creators/avatar-3.jpg',
    tier: 'silver',
    specialties: ['American', 'Vietnamese', 'Chinese'],
    areas_covered: ['Phoenix', 'Ahwatukee', 'Paradise Valley', 'Carefree'],
    rate_range_low: 1000,
    rate_range_high: 2500,
    is_founding_creator: true,
    is_active: true,
    platform_fee_rate: 0.18,
    content_rights_status: 'full_rights',
    created_at: '2024-01-15T09:00:00Z',
  },
  {
    id: 'creator-4',
    display_name: 'Panther Eats',
    slug: 'panther-eats',
    instagram_handle: '@panthereats',
    tiktok_handle: '@panthereats',
    instagram_followers: 43000,
    tiktok_followers: 67000,
    bio: 'ASU student exploring Phoenix. Weekend foodie missions. Affordable eats for the budget.',
    avatar_url: '/creators/avatar-4.jpg',
    tier: 'silver',
    specialties: ['Chinese', 'Mexican', 'American', 'Thai'],
    areas_covered: ['Tempe', 'Phoenix', 'Chandler', 'Mesa'],
    rate_range_low: 800,
    rate_range_high: 1800,
    is_founding_creator: true,
    is_active: true,
    platform_fee_rate: 0.2,
    content_rights_status: 'full_rights',
    created_at: '2024-01-16T10:00:00Z',
  },
  {
    id: 'creator-5',
    display_name: 'Cass Eats',
    slug: 'cass-eats',
    instagram_handle: '@casseats',
    tiktok_handle: '@casseats',
    instagram_followers: 91000,
    tiktok_followers: 156000,
    bio: 'Scottsdale dining expert. Upscale, casual, everything in between. Let\'s eat!',
    avatar_url: '/creators/avatar-5.jpg',
    tier: 'gold',
    specialties: ['Italian', 'Mediterranean', 'American', 'Japanese'],
    areas_covered: ['Scottsdale', 'Paradise Valley', 'Old Town Scottsdale', 'Carefree'],
    rate_range_low: 1800,
    rate_range_high: 4000,
    is_founding_creator: true,
    is_active: true,
    platform_fee_rate: 0.14,
    content_rights_status: 'full_rights',
    created_at: '2024-01-16T10:30:00Z',
  },
];

// SEED RESTAURANTS
export const SEED_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'Barrio Café',
    slug: 'barrio-cafe',
    cuisine_types: ['Mexican'],
    vibe_tags: ['casual', 'family_friendly', 'comfort_food'],
    neighborhood: 'Downtown Phoenix',
    address: '2814 N 16th St, Phoenix, AZ 85016',
    latitude: 33.4667,
    longitude: -112.0833,
    price_range: 2,
    phone: '(602) 636-0240',
    website: 'barriocafe.com',
    menu_url: 'https://barriocafe.com/menu',
    hours: {
      'Monday-Friday': [{ open: '07:00', close: '21:00' }],
      'Saturday': [{ open: '08:00', close: '22:00' }],
      'Sunday': [{ open: '08:00', close: '21:00' }],
    },
    booking_url: '',
    delivery_url: 'https://www.doordash.com',
    instagram_handle: '@barriocafe',
    tiktok_handle: '@barriocafe',
    google_place_id: 'ChIJ8bHg_4-gK4cR_Hqm8_1TmqI',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-2',
    name: 'Pizzeria Bianco',
    slug: 'pizzeria-bianco',
    cuisine_types: ['Italian'],
    vibe_tags: ['casual', 'trendy', 'comfort_food'],
    neighborhood: 'Downtown Phoenix',
    address: '623 E Adams St, Phoenix, AZ 85004',
    latitude: 33.4485,
    longitude: -112.0735,
    price_range: 2,
    phone: '(602) 258-8300',
    website: 'pizzeriabianco.com',
    menu_url: 'https://pizzeriabianco.com/menu',
    hours: {
      'Monday-Thursday': [{ open: '11:00', close: '22:00' }],
      'Friday-Saturday': [{ open: '11:00', close: '23:00' }],
      'Sunday': [{ open: '12:00', close: '22:00' }],
    },
    booking_url: '',
    delivery_url: 'https://www.ubereats.com',
    instagram_handle: '@pizzeriabianco',
    tiktok_handle: '@pizzeriabianco',
    google_place_id: 'ChIJV_Q_V4qgK4cR5hB8o_zQs3A',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-3',
    name: 'Binkley\'s Restaurant',
    slug: 'binkleys-restaurant',
    cuisine_types: ['American'],
    vibe_tags: ['fine_dining', 'romantic', 'upscale'],
    neighborhood: 'Cave Creek',
    address: '6920 E McDonald Dr, Paradise Valley, AZ 85253',
    latitude: 33.6426,
    longitude: -111.9853,
    price_range: 4,
    phone: '(602) 948-4426',
    website: 'binkleysaz.com',
    menu_url: 'https://binkleysaz.com/dining',
    hours: {
      'Tuesday-Thursday': [{ open: '17:00', close: '22:00' }],
      'Friday-Saturday': [{ open: '17:00', close: '23:00' }],
      'Sunday': [{ open: '17:00', close: '22:00' }],
      'Monday': null,
    },
    booking_url: 'https://www.resy.com',
    delivery_url: '',
    instagram_handle: '@binkleysaz',
    tiktok_handle: '',
    google_place_id: 'ChIJ1234567890123',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'premium',
  },
  {
    id: 'rest-4',
    name: 'Hana Japanese Eatery',
    slug: 'hana-japanese-eatery',
    cuisine_types: ['Japanese'],
    vibe_tags: ['casual', 'trendy', 'cozy'],
    neighborhood: 'Phoenix',
    address: '3202 N 7th Ave, Phoenix, AZ 85013',
    latitude: 33.4825,
    longitude: -112.0967,
    price_range: 3,
    phone: '(602) 258-1182',
    website: 'hanajapaneseeatery.com',
    menu_url: 'https://hanajapaneseeatery.com/menu',
    hours: {
      'Monday-Thursday': [{ open: '11:00', close: '22:00' }],
      'Friday-Saturday': [{ open: '11:00', close: '23:30' }],
      'Sunday': [{ open: '11:00', close: '22:00' }],
    },
    booking_url: '',
    delivery_url: 'https://www.ubereats.com',
    instagram_handle: '@hanajapaneseeatery',
    tiktok_handle: '@hanajapanese',
    google_place_id: 'ChIJ5432167890123',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-5',
    name: 'Hash Kitchen',
    slug: 'hash-kitchen',
    cuisine_types: ['American'],
    vibe_tags: ['casual', 'family_friendly', 'fast_casual'],
    neighborhood: 'Scottsdale',
    address: '6245 N Scottsdale Rd, Scottsdale, AZ 85253',
    latitude: 33.5,
    longitude: -111.9,
    price_range: 2,
    phone: '(480) 999-4200',
    website: 'hashkitchen.com',
    menu_url: 'https://hashkitchen.com/menu',
    hours: {
      'Monday-Sunday': [{ open: '07:00', close: '22:00' }],
    },
    booking_url: '',
    delivery_url: 'https://www.doordash.com',
    instagram_handle: '@hashkitchen',
    tiktok_handle: '@hashkitchen',
    google_place_id: 'ChIJ6789012345678',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-6',
    name: 'The Sicilian Butcher',
    slug: 'the-sicilian-butcher',
    cuisine_types: ['Italian'],
    vibe_tags: ['upscale', 'romantic', 'fine_dining'],
    neighborhood: 'Scottsdale',
    address: '7114 E Stetson Dr, Scottsdale, AZ 85251',
    latitude: 33.495,
    longitude: -111.925,
    price_range: 4,
    phone: '(480) 990-3773',
    website: 'thesicilianbutcher.com',
    menu_url: 'https://thesicilianbutcher.com/menu',
    hours: {
      'Monday-Thursday': [{ open: '17:00', close: '22:00' }],
      'Friday-Saturday': [{ open: '17:00', close: '23:00' }],
      'Sunday': [{ open: '17:00', close: '21:00' }],
    },
    booking_url: 'https://www.resy.com',
    delivery_url: '',
    instagram_handle: '@thesicilianbutcher',
    tiktok_handle: '',
    google_place_id: 'ChIJ0123456789012',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'premium',
  },
  {
    id: 'rest-7',
    name: 'Chino Bandido',
    slug: 'chino-bandido',
    cuisine_types: ['Chinese', 'Mexican'],
    vibe_tags: ['casual', 'trendy', 'social'],
    neighborhood: 'Phoenix',
    address: '2002 N 7th St, Phoenix, AZ 85006',
    latitude: 33.4542,
    longitude: -112.0788,
    price_range: 2,
    phone: '(602) 266-3585',
    website: 'chinobandido.com',
    menu_url: 'https://chinobandido.com/menu',
    hours: {
      'Monday-Sunday': [{ open: '11:00', close: '22:00' }],
    },
    booking_url: '',
    delivery_url: 'https://www.ubereats.com',
    instagram_handle: '@chinobandido',
    tiktok_handle: '@chinobandido',
    google_place_id: 'ChIJ9876543210987',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-8',
    name: 'The Mission',
    slug: 'the-mission',
    cuisine_types: ['Mexican'],
    vibe_tags: ['casual', 'social', 'trendy'],
    neighborhood: 'Old Town Scottsdale',
    address: '3815 N Brown Ave, Scottsdale, AZ 85251',
    latitude: 33.494,
    longitude: -111.926,
    price_range: 3,
    phone: '(480) 636-5005',
    website: 'themissionaz.com',
    menu_url: 'https://themissionaz.com/menu',
    hours: {
      'Monday-Thursday': [{ open: '11:00', close: '23:00' }],
      'Friday-Saturday': [{ open: '11:00', close: '00:00' }],
      'Sunday': [{ open: '11:00', close: '23:00' }],
    },
    booking_url: '',
    delivery_url: 'https://www.doordash.com',
    instagram_handle: '@themissionaz',
    tiktok_handle: '@themissionaz',
    google_place_id: 'ChIJ5432109876543',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-9',
    name: 'Aunt Chilada\'s',
    slug: 'aunt-chiladas',
    cuisine_types: ['Mexican'],
    vibe_tags: ['casual', 'family_friendly', 'comfort_food'],
    neighborhood: 'Phoenix',
    address: '8005 S 48th St, Phoenix, AZ 85044',
    latitude: 33.298,
    longitude: -112.146,
    price_range: 2,
    phone: '(602) 431-1915',
    website: 'auntchiladas.com',
    menu_url: 'https://auntchiladas.com/menu',
    hours: {
      'Monday-Sunday': [{ open: '11:00', close: '21:00' }],
    },
    booking_url: '',
    delivery_url: 'https://www.doordash.com',
    instagram_handle: '@auntchiladas',
    tiktok_handle: '',
    google_place_id: 'ChIJ0987654321098',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-10',
    name: 'Farm & Craft',
    slug: 'farm-and-craft',
    cuisine_types: ['American', 'Mediterranean'],
    vibe_tags: ['healthy', 'trendy', 'upscale'],
    neighborhood: 'Scottsdale',
    address: '7373 Scottsdale Mall, Scottsdale, AZ 85251',
    latitude: 33.497,
    longitude: -111.923,
    price_range: 3,
    phone: '(480) 990-0800',
    website: 'farmandcraft.com',
    menu_url: 'https://farmandcraft.com/menu',
    hours: {
      'Monday-Sunday': [{ open: '11:00', close: '22:00' }],
    },
    booking_url: 'https://www.opentable.com',
    delivery_url: 'https://www.ubereats.com',
    instagram_handle: '@farmandcraft',
    tiktok_handle: '@farmandcraft',
    google_place_id: 'ChIJ2109876543210',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-11',
    name: 'Dick\'s Hideaway',
    slug: 'dicks-hideaway',
    cuisine_types: ['American'],
    vibe_tags: ['casual', 'comfort_food', 'social'],
    neighborhood: 'Phoenix',
    address: '6110 N Central Ave, Phoenix, AZ 85012',
    latitude: 33.501,
    longitude: -112.074,
    price_range: 2,
    phone: '(602) 241-1959',
    website: 'dickshideaway.com',
    menu_url: 'https://dickshideaway.com/menu',
    hours: {
      'Monday-Sunday': [{ open: '11:00', close: '23:00' }],
    },
    booking_url: '',
    delivery_url: 'https://www.doordash.com',
    instagram_handle: '@dickshideaway',
    tiktok_handle: '',
    google_place_id: 'ChIJ3210987654321',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-12',
    name: 'Pane Bianco',
    slug: 'pane-bianco',
    cuisine_types: ['Italian'],
    vibe_tags: ['casual', 'cozy', 'trendy'],
    neighborhood: 'Downtown Phoenix',
    address: '112 W Pierce St, Phoenix, AZ 85004',
    latitude: 33.456,
    longitude: -112.078,
    price_range: 2,
    phone: '(602) 234-2100',
    website: 'panebiancoaz.com',
    menu_url: 'https://panebiancoaz.com/menu',
    hours: {
      'Monday-Friday': [{ open: '07:00', close: '20:00' }],
      'Saturday': [{ open: '08:00', close: '20:00' }],
      'Sunday': null,
    },
    booking_url: '',
    delivery_url: '',
    instagram_handle: '@panebianco',
    tiktok_handle: '',
    google_place_id: 'ChIJ4321098765432',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
  {
    id: 'rest-13',
    name: 'SumoMaya',
    slug: 'sumomaya',
    cuisine_types: ['Japanese'],
    vibe_tags: ['trendy', 'upscale', 'social'],
    neighborhood: 'Scottsdale',
    address: '7000 E Camelback Rd, Scottsdale, AZ 85251',
    latitude: 33.503,
    longitude: -111.918,
    price_range: 3,
    phone: '(480) 949-7866',
    website: 'sumomaya.com',
    menu_url: 'https://sumomaya.com/menu',
    hours: {
      'Monday-Thursday': [{ open: '17:00', close: '22:00' }],
      'Friday-Saturday': [{ open: '17:00', close: '23:00' }],
      'Sunday': [{ open: '17:00', close: '22:00' }],
    },
    booking_url: 'https://www.opentable.com',
    delivery_url: 'https://www.ubereats.com',
    instagram_handle: '@sumomaya',
    tiktok_handle: '@sumomaya',
    google_place_id: 'ChIJ5432109876543',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'premium',
  },
  {
    id: 'rest-14',
    name: 'The Montauk',
    slug: 'the-montauk',
    cuisine_types: ['American', 'Mediterranean'],
    vibe_tags: ['upscale', 'romantic', 'date_night'],
    neighborhood: 'Scottsdale',
    address: '10104 N Scottsdale Rd, Scottsdale, AZ 85253',
    latitude: 33.51,
    longitude: -111.896,
    price_range: 4,
    phone: '(480) 636-7111',
    website: 'themontauk.com',
    menu_url: 'https://themontauk.com/menu',
    hours: {
      'Monday-Thursday': [{ open: '17:00', close: '22:00' }],
      'Friday-Saturday': [{ open: '17:00', close: '23:00' }],
      'Sunday': [{ open: '17:00', close: '21:00' }],
    },
    booking_url: 'https://www.resy.com',
    delivery_url: '',
    instagram_handle: '@themontauk',
    tiktok_handle: '',
    google_place_id: 'ChIJ6543210987654',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'premium',
  },
  {
    id: 'rest-15',
    name: 'Little Miss BBQ',
    slug: 'little-miss-bbq',
    cuisine_types: ['American'],
    vibe_tags: ['casual', 'comfort_food', 'social'],
    neighborhood: 'Phoenix',
    address: '2929 N 24th St, Phoenix, AZ 85008',
    latitude: 33.478,
    longitude: -112.063,
    price_range: 2,
    phone: '(602) 955-3227',
    website: 'littlemissbbq.com',
    menu_url: 'https://littlemissbbq.com/menu',
    hours: {
      'Monday': null,
      'Tuesday-Saturday': [{ open: '11:00', close: '21:00' }],
      'Sunday': [{ open: '12:00', close: '19:00' }],
    },
    booking_url: '',
    delivery_url: 'https://www.doordash.com',
    instagram_handle: '@littlemissbbq',
    tiktok_handle: '@littlemissbbq',
    google_place_id: 'ChIJ7654321098765',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    subscription_tier: 'standard',
  },
];

// SEED CONTENT
export const SEED_CONTENT: Content[] = [
  {
    id: 'content-1',
    creator_id: 'creator-1',
    restaurant_id: 'rest-2',
    content_type: 'video' as ContentType,
    media_url: '/content/pizzeria-bianco-1.mp4',
    thumbnail_url: '/content/pizzeria-bianco-1-thumb.jpg',
    duration_seconds: 45,
    aspect_ratio: '9:16',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/hungryhotline/123456',
    caption: 'This Margherita pizza at Pizzeria Bianco hits different. Thin crust, fresh mozzarella, basil perfection. 🍕',
    cuisine_tags: ['Italian'],
    vibe_tags: ['casual', 'comfort_food', 'trendy'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-23T15:30:00Z',
    created_at: '2024-03-23T15:30:00Z',
    is_active: true,
    view_count: 12450,
    save_count: 890,
    tap_count: 340,
  },
  {
    id: 'content-2',
    creator_id: 'creator-2',
    restaurant_id: 'rest-1',
    content_type: 'photo' as ContentType,
    media_url: '/content/barrio-cafe-1.jpg',
    thumbnail_url: '/content/barrio-cafe-1-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '4:3',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/tastesofaz/234567',
    caption: 'Chilaquiles at Barrio Café are insane. House-made tortilla chips, slow roasted chicken, oaxaca cheese. Pure Arizona comfort food.',
    cuisine_tags: ['Mexican'],
    vibe_tags: ['family_friendly', 'comfort_food', 'casual'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-22T12:00:00Z',
    created_at: '2024-03-22T12:00:00Z',
    is_active: true,
    view_count: 23100,
    save_count: 1540,
    tap_count: 620,
  },
  {
    id: 'content-3',
    creator_id: 'creator-3',
    restaurant_id: 'rest-4',
    content_type: 'video' as ContentType,
    media_url: '/content/hana-1.mp4',
    thumbnail_url: '/content/hana-1-thumb.jpg',
    duration_seconds: 30,
    aspect_ratio: '9:16',
    original_platform: 'tiktok',
    original_url: 'https://tiktok.com/@azfoodguy/987654',
    caption: 'Spicy tuna roll at Hana hits hard. Fresh tuna, sriracha mayo, super crispy. Worth the wait.',
    cuisine_tags: ['Japanese'],
    vibe_tags: ['casual', 'cozy', 'trendy'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: false,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 180,
    rights_expiry_date: '2024-09-23T00:00:00Z',
    publish_date: '2024-03-21T18:45:00Z',
    created_at: '2024-03-21T18:45:00Z',
    is_active: true,
    view_count: 5670,
    save_count: 340,
    tap_count: 180,
  },
  {
    id: 'content-4',
    creator_id: 'creator-4',
    restaurant_id: 'rest-5',
    content_type: 'photo' as ContentType,
    media_url: '/content/hash-kitchen-1.jpg',
    thumbnail_url: '/content/hash-kitchen-1-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '1:1',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/panthereats/345678',
    caption: 'Hash Kitchen breakfast is a college budget lifesaver. The Birdie Benedict is massive and only $12. ASU approved 🏀',
    cuisine_tags: ['American'],
    vibe_tags: ['family_friendly', 'fast_casual'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-20T09:15:00Z',
    created_at: '2024-03-20T09:15:00Z',
    is_active: true,
    view_count: 8920,
    save_count: 720,
    tap_count: 290,
  },
  {
    id: 'content-5',
    creator_id: 'creator-5',
    restaurant_id: 'rest-6',
    content_type: 'video' as ContentType,
    media_url: '/content/sicilian-butcher-1.mp4',
    thumbnail_url: '/content/sicilian-butcher-1-thumb.jpg',
    duration_seconds: 60,
    aspect_ratio: '9:16',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/casseats/456789',
    caption: 'The Sicilian Butcher never misses. This pasta is ridiculously good. Carbonara that tastes like Rome.',
    cuisine_tags: ['Italian'],
    vibe_tags: ['upscale', 'romantic', 'fine_dining'],
    sponsorship_status: 'comped' as SponsorshipStatus,
    disclosure_status: '#ad',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-19T19:30:00Z',
    created_at: '2024-03-19T19:30:00Z',
    is_active: true,
    view_count: 34560,
    save_count: 2890,
    tap_count: 1120,
  },
  {
    id: 'content-6',
    creator_id: 'creator-1',
    restaurant_id: 'rest-7',
    content_type: 'photo' as ContentType,
    media_url: '/content/chino-bandido-1.jpg',
    thumbnail_url: '/content/chino-bandido-1-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '9:16',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/hungryhotline/567890',
    caption: 'Chino Bandido is peak fusion. Kung Pao chicken burrito? Yes. And it slaps.',
    cuisine_tags: ['Chinese', 'Mexican'],
    vibe_tags: ['casual', 'trendy', 'social'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: false,
    rights_paid_amplification: false,
    rights_duration: 180,
    rights_expiry_date: '2024-09-23T00:00:00Z',
    publish_date: '2024-03-18T14:20:00Z',
    created_at: '2024-03-18T14:20:00Z',
    is_active: true,
    view_count: 7890,
    save_count: 610,
    tap_count: 240,
  },
  {
    id: 'content-7',
    creator_id: 'creator-2',
    restaurant_id: 'rest-8',
    content_type: 'video' as ContentType,
    media_url: '/content/the-mission-1.mp4',
    thumbnail_url: '/content/the-mission-1-thumb.jpg',
    duration_seconds: 45,
    aspect_ratio: '1:1',
    original_platform: 'tiktok',
    original_url: 'https://tiktok.com/@tastesofaz/678901',
    caption: 'The Mission margaritas are legendary. Fresh lime, agave, tequila perfection. Old Town Scottsdale hits right.',
    cuisine_tags: ['Mexican'],
    vibe_tags: ['casual', 'social', 'trendy'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-17T20:00:00Z',
    created_at: '2024-03-17T20:00:00Z',
    is_active: true,
    view_count: 45230,
    save_count: 3120,
    tap_count: 1890,
  },
  {
    id: 'content-8',
    creator_id: 'creator-3',
    restaurant_id: 'rest-9',
    content_type: 'photo' as ContentType,
    media_url: '/content/aunt-chiladas-1.jpg',
    thumbnail_url: '/content/aunt-chiladas-1-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '4:3',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/azfoodguy/789012',
    caption: 'Aunt Chilada\'s green chile is life-changing. This has been a Phoenix staple for decades. Respect.',
    cuisine_tags: ['Mexican'],
    vibe_tags: ['family_friendly', 'comfort_food'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-16T11:30:00Z',
    created_at: '2024-03-16T11:30:00Z',
    is_active: true,
    view_count: 6720,
    save_count: 450,
    tap_count: 210,
  },
  {
    id: 'content-9',
    creator_id: 'creator-4',
    restaurant_id: 'rest-10',
    content_type: 'video' as ContentType,
    media_url: '/content/farm-craft-1.mp4',
    thumbnail_url: '/content/farm-craft-1-thumb.jpg',
    duration_seconds: 35,
    aspect_ratio: '9:16',
    original_platform: 'tiktok',
    original_url: 'https://tiktok.com/@panthereats/890123',
    caption: 'Farm & Craft healthy bowls hit different when you\'re trying to eat clean. Fresh, local, tasty.',
    cuisine_tags: ['American', 'Mediterranean'],
    vibe_tags: ['healthy', 'trendy', 'upscale'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: false,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 180,
    rights_expiry_date: '2024-09-23T00:00:00Z',
    publish_date: '2024-03-15T16:45:00Z',
    created_at: '2024-03-15T16:45:00Z',
    is_active: true,
    view_count: 4560,
    save_count: 560,
    tap_count: 180,
  },
  {
    id: 'content-10',
    creator_id: 'creator-5',
    restaurant_id: 'rest-11',
    content_type: 'photo' as ContentType,
    media_url: '/content/dicks-hideaway-1.jpg',
    thumbnail_url: '/content/dicks-hideaway-1-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '1:1',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/casseats/901234',
    caption: 'Dick\'s Hideaway is Scottsdale\'s hidden gem. Casual vibe, great cocktails, even better nachos.',
    cuisine_tags: ['American'],
    vibe_tags: ['casual', 'comfort_food', 'social'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-14T19:00:00Z',
    created_at: '2024-03-14T19:00:00Z',
    is_active: true,
    view_count: 12340,
    save_count: 890,
    tap_count: 420,
  },
  {
    id: 'content-11',
    creator_id: 'creator-1',
    restaurant_id: 'rest-12',
    content_type: 'video' as ContentType,
    media_url: '/content/pane-bianco-1.mp4',
    thumbnail_url: '/content/pane-bianco-1-thumb.jpg',
    duration_seconds: 40,
    aspect_ratio: '9:16',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/hungryhotline/012345',
    caption: 'Pane Bianco sandwiches are architectural masterpieces. Simple ingredients, perfect execution. Always lines out the door.',
    cuisine_tags: ['Italian'],
    vibe_tags: ['casual', 'cozy', 'trendy'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-13T10:15:00Z',
    created_at: '2024-03-13T10:15:00Z',
    is_active: true,
    view_count: 18900,
    save_count: 1340,
    tap_count: 560,
  },
  {
    id: 'content-12',
    creator_id: 'creator-2',
    restaurant_id: 'rest-13',
    content_type: 'photo' as ContentType,
    media_url: '/content/sumomaya-1.jpg',
    thumbnail_url: '/content/sumomaya-1-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '9:16',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/tastesofaz/123456',
    caption: 'SumoMaya is bringing upscale Asian fusion to Scottsdale. The sushi is pristine, the atmosphere is immaculate.',
    cuisine_tags: ['Japanese'],
    vibe_tags: ['trendy', 'upscale', 'social'],
    sponsorship_status: 'comped' as SponsorshipStatus,
    disclosure_status: '#partnership',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-12T18:30:00Z',
    created_at: '2024-03-12T18:30:00Z',
    is_active: true,
    view_count: 28900,
    save_count: 2120,
    tap_count: 890,
  },
  {
    id: 'content-13',
    creator_id: 'creator-3',
    restaurant_id: 'rest-14',
    content_type: 'video' as ContentType,
    media_url: '/content/the-montauk-1.mp4',
    thumbnail_url: '/content/the-montauk-1-thumb.jpg',
    duration_seconds: 50,
    aspect_ratio: '1:1',
    original_platform: 'tiktok',
    original_url: 'https://tiktok.com/@azfoodguy/234567',
    caption: 'The Montauk is peak date night energy. Seafood perfection, wine list for days, ambiance 10/10.',
    cuisine_tags: ['American', 'Mediterranean'],
    vibe_tags: ['upscale', 'romantic', 'date_night'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-11T20:45:00Z',
    created_at: '2024-03-11T20:45:00Z',
    is_active: true,
    view_count: 32100,
    save_count: 2340,
    tap_count: 980,
  },
  {
    id: 'content-14',
    creator_id: 'creator-4',
    restaurant_id: 'rest-15',
    content_type: 'photo' as ContentType,
    media_url: '/content/little-miss-bbq-1.jpg',
    thumbnail_url: '/content/little-miss-bbq-1-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '4:3',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/panthereats/345678',
    caption: 'Little Miss BBQ pulled pork is melt-in-your-mouth goodness. Smoke perfection. Best value in Phoenix.',
    cuisine_tags: ['American'],
    vibe_tags: ['casual', 'comfort_food', 'social'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-10T13:20:00Z',
    created_at: '2024-03-10T13:20:00Z',
    is_active: true,
    view_count: 9870,
    save_count: 720,
    tap_count: 340,
  },
  {
    id: 'content-15',
    creator_id: 'creator-5',
    restaurant_id: 'rest-1',
    content_type: 'video' as ContentType,
    media_url: '/content/barrio-cafe-2.mp4',
    thumbnail_url: '/content/barrio-cafe-2-thumb.jpg',
    duration_seconds: 35,
    aspect_ratio: '9:16',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/casseats/456789',
    caption: 'Barrio Café eggs rancheros are legendary. Phoenix institution. The perfect breakfast.',
    cuisine_tags: ['Mexican'],
    vibe_tags: ['family_friendly', 'comfort_food', 'casual'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-09T09:00:00Z',
    created_at: '2024-03-09T09:00:00Z',
    is_active: true,
    view_count: 15670,
    save_count: 1120,
    tap_count: 480,
  },
  {
    id: 'content-16',
    creator_id: 'creator-1',
    restaurant_id: 'rest-3',
    content_type: 'photo' as ContentType,
    media_url: '/content/binkleys-1.jpg',
    thumbnail_url: '/content/binkleys-1-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '9:16',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/hungryhotline/567890',
    caption: 'Binkley\'s is next level fine dining. Every course is a work of art. Worth every penny.',
    cuisine_tags: ['American'],
    vibe_tags: ['fine_dining', 'romantic', 'upscale'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: false,
    rights_paid_amplification: false,
    rights_duration: 180,
    rights_expiry_date: '2024-09-23T00:00:00Z',
    publish_date: '2024-03-08T19:15:00Z',
    created_at: '2024-03-08T19:15:00Z',
    is_active: true,
    view_count: 11230,
    save_count: 890,
    tap_count: 340,
  },
  {
    id: 'content-17',
    creator_id: 'creator-2',
    restaurant_id: 'rest-2',
    content_type: 'video' as ContentType,
    media_url: '/content/pizzeria-bianco-2.mp4',
    thumbnail_url: '/content/pizzeria-bianco-2-thumb.jpg',
    duration_seconds: 40,
    aspect_ratio: '1:1',
    original_platform: 'tiktok',
    original_url: 'https://tiktok.com/@tastesofaz/678901',
    caption: 'Pizzeria Bianco Al Taglio by the slice game is undefeated. Multiple options, all incredible.',
    cuisine_tags: ['Italian'],
    vibe_tags: ['casual', 'trendy', 'comfort_food'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-07T12:30:00Z',
    created_at: '2024-03-07T12:30:00Z',
    is_active: true,
    view_count: 19870,
    save_count: 1340,
    tap_count: 620,
  },
  {
    id: 'content-18',
    creator_id: 'creator-3',
    restaurant_id: 'rest-5',
    content_type: 'photo' as ContentType,
    media_url: '/content/hash-kitchen-2.jpg',
    thumbnail_url: '/content/hash-kitchen-2-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '1:1',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/azfoodguy/789012',
    caption: 'Hash Kitchen Redeye is the answer to boring coffee. Hash brown inside, bacon, egg, all the goods.',
    cuisine_tags: ['American'],
    vibe_tags: ['family_friendly', 'fast_casual', 'comfort_food'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-06T08:00:00Z',
    created_at: '2024-03-06T08:00:00Z',
    is_active: true,
    view_count: 7650,
    save_count: 540,
    tap_count: 210,
  },
  {
    id: 'content-19',
    creator_id: 'creator-4',
    restaurant_id: 'rest-8',
    content_type: 'video' as ContentType,
    media_url: '/content/the-mission-2.mp4',
    thumbnail_url: '/content/the-mission-2-thumb.jpg',
    duration_seconds: 45,
    aspect_ratio: '9:16',
    original_platform: 'tiktok',
    original_url: 'https://tiktok.com/@panthereats/890123',
    caption: 'The Mission street tacos are dangerously good. Fresh meat, perfect salsas, come hungry.',
    cuisine_tags: ['Mexican'],
    vibe_tags: ['casual', 'social', 'trendy'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: false,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 180,
    rights_expiry_date: '2024-09-23T00:00:00Z',
    publish_date: '2024-03-05T17:45:00Z',
    created_at: '2024-03-05T17:45:00Z',
    is_active: true,
    view_count: 13450,
    save_count: 920,
    tap_count: 450,
  },
  {
    id: 'content-20',
    creator_id: 'creator-5',
    restaurant_id: 'rest-6',
    content_type: 'photo' as ContentType,
    media_url: '/content/sicilian-butcher-2.jpg',
    thumbnail_url: '/content/sicilian-butcher-2-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '4:3',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/casseats/901234',
    caption: 'The Sicilian Butcher tomahawk ribeye is a statement. Perfectly seared, incredible flavor, steakhouse goals.',
    cuisine_tags: ['Italian', 'American'],
    vibe_tags: ['upscale', 'fine_dining', 'romantic'],
    sponsorship_status: 'comped' as SponsorshipStatus,
    disclosure_status: '#ad',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-04T20:00:00Z',
    created_at: '2024-03-04T20:00:00Z',
    is_active: true,
    view_count: 42300,
    save_count: 3120,
    tap_count: 1450,
  },
  {
    id: 'content-21',
    creator_id: 'creator-1',
    restaurant_id: 'rest-4',
    content_type: 'video' as ContentType,
    media_url: '/content/hana-2.mp4',
    thumbnail_url: '/content/hana-2-thumb.jpg',
    duration_seconds: 35,
    aspect_ratio: '1:1',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/hungryhotline/012345',
    caption: 'Hana ramen broth is liquid gold. Perfectly balanced, noodles cooked to order, toppings on point.',
    cuisine_tags: ['Japanese'],
    vibe_tags: ['casual', 'cozy', 'trendy'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-03T14:30:00Z',
    created_at: '2024-03-03T14:30:00Z',
    is_active: true,
    view_count: 8900,
    save_count: 620,
    tap_count: 280,
  },
  {
    id: 'content-22',
    creator_id: 'creator-2',
    restaurant_id: 'rest-7',
    content_type: 'photo' as ContentType,
    media_url: '/content/chino-bandido-2.jpg',
    thumbnail_url: '/content/chino-bandido-2-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '9:16',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/tastesofaz/234567',
    caption: 'Chino Bandido Vietnamese banh mi burrito is wild in the best way. Pickled veggies, pâté, crispy, fresh.',
    cuisine_tags: ['Chinese', 'Mexican'],
    vibe_tags: ['trendy', 'casual', 'social'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-02T11:00:00Z',
    created_at: '2024-03-02T11:00:00Z',
    is_active: true,
    view_count: 12450,
    save_count: 890,
    tap_count: 380,
  },
  {
    id: 'content-23',
    creator_id: 'creator-3',
    restaurant_id: 'rest-10',
    content_type: 'video' as ContentType,
    media_url: '/content/farm-craft-2.mp4',
    thumbnail_url: '/content/farm-craft-2-thumb.jpg',
    duration_seconds: 40,
    aspect_ratio: '9:16',
    original_platform: 'tiktok',
    original_url: 'https://tiktok.com/@azfoodguy/345678',
    caption: 'Farm & Craft seasonal salad is a showstopper. Heirloom tomatoes, fresh greens, house made dressing.',
    cuisine_tags: ['American', 'Mediterranean'],
    vibe_tags: ['healthy', 'trendy', 'upscale'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-03-01T15:15:00Z',
    created_at: '2024-03-01T15:15:00Z',
    is_active: true,
    view_count: 6780,
    save_count: 480,
    tap_count: 190,
  },
  {
    id: 'content-24',
    creator_id: 'creator-4',
    restaurant_id: 'rest-12',
    content_type: 'photo' as ContentType,
    media_url: '/content/pane-bianco-2.jpg',
    thumbnail_url: '/content/pane-bianco-2-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '1:1',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/panthereats/567890',
    caption: 'Pane Bianco mortadella sandwich might be the best sandwich in Arizona. Fight me.',
    cuisine_tags: ['Italian'],
    vibe_tags: ['casual', 'cozy', 'comfort_food'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-02-29T10:45:00Z',
    created_at: '2024-02-29T10:45:00Z',
    is_active: true,
    view_count: 14560,
    save_count: 1020,
    tap_count: 450,
  },
  {
    id: 'content-25',
    creator_id: 'creator-5',
    restaurant_id: 'rest-13',
    content_type: 'video' as ContentType,
    media_url: '/content/sumomaya-2.mp4',
    thumbnail_url: '/content/sumomaya-2-thumb.jpg',
    duration_seconds: 50,
    aspect_ratio: '1:1',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/casseats/678901',
    caption: 'SumoMaya tuna tataki is the start to an incredible meal. Seared to perfection, elegant plating.',
    cuisine_tags: ['Japanese'],
    vibe_tags: ['upscale', 'trendy', 'fine_dining'],
    sponsorship_status: 'comped' as SponsorshipStatus,
    disclosure_status: '#partnership',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-02-28T18:00:00Z',
    created_at: '2024-02-28T18:00:00Z',
    is_active: true,
    view_count: 26540,
    save_count: 1890,
    tap_count: 780,
  },
  {
    id: 'content-26',
    creator_id: 'creator-1',
    restaurant_id: 'rest-11',
    content_type: 'photo' as ContentType,
    media_url: '/content/dicks-hideaway-2.jpg',
    thumbnail_url: '/content/dicks-hideaway-2-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '4:3',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/hungryhotline/789012',
    caption: 'Dick\'s Hideaway espresso martini is smooth. Vintage vibe, great bartenders, killer drinks.',
    cuisine_tags: ['American'],
    vibe_tags: ['casual', 'social', 'cozy'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-02-27T21:30:00Z',
    created_at: '2024-02-27T21:30:00Z',
    is_active: true,
    view_count: 9670,
    save_count: 680,
    tap_count: 310,
  },
  {
    id: 'content-27',
    creator_id: 'creator-2',
    restaurant_id: 'rest-9',
    content_type: 'video' as ContentType,
    media_url: '/content/aunt-chiladas-2.mp4',
    thumbnail_url: '/content/aunt-chiladas-2-thumb.jpg',
    duration_seconds: 45,
    aspect_ratio: '9:16',
    original_platform: 'tiktok',
    original_url: 'https://tiktok.com/@tastesofaz/890123',
    caption: 'Aunt Chilada\'s enchiladas rojo are perfection. Three generations of recipes in this place.',
    cuisine_tags: ['Mexican'],
    vibe_tags: ['family_friendly', 'comfort_food', 'casual'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-02-26T12:15:00Z',
    created_at: '2024-02-26T12:15:00Z',
    is_active: true,
    view_count: 11230,
    save_count: 780,
    tap_count: 340,
  },
  {
    id: 'content-28',
    creator_id: 'creator-3',
    restaurant_id: 'rest-14',
    content_type: 'photo' as ContentType,
    media_url: '/content/the-montauk-2.jpg',
    thumbnail_url: '/content/the-montauk-2-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '9:16',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/azfoodguy/901234',
    caption: 'The Montauk happy hour is a steal. Oysters, cocktails, sunset views. Heaven.',
    cuisine_tags: ['American', 'Mediterranean'],
    vibe_tags: ['upscale', 'social', 'date_night'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: true,
    rights_paid_amplification: true,
    rights_duration: 365,
    rights_expiry_date: '2025-03-23T00:00:00Z',
    publish_date: '2024-02-25T17:00:00Z',
    created_at: '2024-02-25T17:00:00Z',
    is_active: true,
    view_count: 15890,
    save_count: 1120,
    tap_count: 560,
  },
  {
    id: 'content-29',
    creator_id: 'creator-4',
    restaurant_id: 'rest-15',
    content_type: 'video' as ContentType,
    media_url: '/content/little-miss-bbq-2.mp4',
    thumbnail_url: '/content/little-miss-bbq-2-thumb.jpg',
    duration_seconds: 35,
    aspect_ratio: '9:16',
    original_platform: 'tiktok',
    original_url: 'https://tiktok.com/@panthereats/012345',
    caption: 'Little Miss BBQ brisket is smoking hot (literally). Bark is crispy, meat is tender, dreams are real.',
    cuisine_tags: ['American'],
    vibe_tags: ['casual', 'comfort_food'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: false,
    rights_restaurant_repost: true,
    rights_paid_amplification: false,
    rights_duration: 180,
    rights_expiry_date: '2024-09-23T00:00:00Z',
    publish_date: '2024-02-24T13:45:00Z',
    created_at: '2024-02-24T13:45:00Z',
    is_active: true,
    view_count: 8450,
    save_count: 620,
    tap_count: 280,
  },
  {
    id: 'content-30',
    creator_id: 'creator-5',
    restaurant_id: 'rest-3',
    content_type: 'photo' as ContentType,
    media_url: '/content/binkleys-2.jpg',
    thumbnail_url: '/content/binkleys-2-thumb.jpg',
    duration_seconds: 0,
    aspect_ratio: '1:1',
    original_platform: 'instagram',
    original_url: 'https://instagram.com/casseats/123456',
    caption: 'Binkley\'s 20-course tasting menu is a culinary experience. Each course surprises you. Worth the reservation.',
    cuisine_tags: ['American'],
    vibe_tags: ['fine_dining', 'upscale', 'romantic'],
    sponsorship_status: 'organic' as SponsorshipStatus,
    disclosure_status: '',
    rights_platform_display: true,
    rights_platform_reshare: true,
    rights_restaurant_repost: false,
    rights_paid_amplification: false,
    rights_duration: 180,
    rights_expiry_date: '2024-09-23T00:00:00Z',
    publish_date: '2024-02-23T19:45:00Z',
    created_at: '2024-02-23T19:45:00Z',
    is_active: true,
    view_count: 13670,
    save_count: 980,
    tap_count: 420,
  },
];

// SEED DISHES
export const SEED_DISHES: Dish[] = [
  // Pizzeria Bianco
  {
    id: 'dish-1',
    restaurant_id: 'rest-2',
    name: 'Margherita Pizza',
    slug: 'margherita-pizza',
    category: 'Entree',
    price: 18,
    description: 'Classic Neapolitan style with fresh mozzarella, basil, and tomato sauce',
    thumbnail_url: '/dishes/margherita-pizza.jpg',
    feature_count: 5,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-2',
    restaurant_id: 'rest-2',
    name: 'Al Taglio Focaccia',
    slug: 'al-taglio-focaccia',
    category: 'Appetizer',
    price: 6,
    description: 'Italian focaccia by the slice with various toppings',
    thumbnail_url: '/dishes/focaccia.jpg',
    feature_count: 3,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Barrio Café
  {
    id: 'dish-3',
    restaurant_id: 'rest-1',
    name: 'Chilaquiles',
    slug: 'chilaquiles',
    category: 'Entree',
    price: 14,
    description: 'House-made tortilla chips with slow roasted chicken, oaxaca cheese',
    thumbnail_url: '/dishes/chilaquiles.jpg',
    feature_count: 8,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-4',
    restaurant_id: 'rest-1',
    name: 'Eggs Rancheros',
    slug: 'eggs-rancheros',
    category: 'Entree',
    price: 12,
    description: 'Fried eggs with ranchero sauce, beans, and tortillas',
    thumbnail_url: '/dishes/eggs-rancheros.jpg',
    feature_count: 6,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-5',
    restaurant_id: 'rest-1',
    name: 'Chile Relleno',
    slug: 'chile-relleno',
    category: 'Entree',
    price: 16,
    description: 'Roasted poblano pepper filled with cheese and topped with ranchero sauce',
    thumbnail_url: '/dishes/chile-relleno.jpg',
    feature_count: 4,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Hana Japanese
  {
    id: 'dish-6',
    restaurant_id: 'rest-4',
    name: 'Spicy Tuna Roll',
    slug: 'spicy-tuna-roll',
    category: 'Entree',
    price: 11,
    description: 'Fresh tuna, sriracha mayo, crispy exterior',
    thumbnail_url: '/dishes/spicy-tuna-roll.jpg',
    feature_count: 7,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-7',
    restaurant_id: 'rest-4',
    name: 'Tonkotsu Ramen',
    slug: 'tonkotsu-ramen',
    category: 'Entree',
    price: 14,
    description: 'Rich pork bone broth with noodles, pork belly, egg',
    thumbnail_url: '/dishes/tonkotsu-ramen.jpg',
    feature_count: 9,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Hash Kitchen
  {
    id: 'dish-8',
    restaurant_id: 'rest-5',
    name: 'Birdie Benedict',
    slug: 'birdie-benedict',
    category: 'Entree',
    price: 12,
    description: 'English muffin, turkey, poached eggs, hollandaise, hash browns',
    thumbnail_url: '/dishes/birdie-benedict.jpg',
    feature_count: 6,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-9',
    restaurant_id: 'rest-5',
    name: 'Redeye Hash',
    slug: 'redeye-hash',
    category: 'Entree',
    price: 13,
    description: 'Hash browns baked inside, bacon, fried eggs, melted cheese',
    thumbnail_url: '/dishes/redeye-hash.jpg',
    feature_count: 5,
    created_at: '2024-01-01T00:00:00Z',
  },
  // The Sicilian Butcher
  {
    id: 'dish-10',
    restaurant_id: 'rest-6',
    name: 'Carbonara Pasta',
    slug: 'carbonara-pasta',
    category: 'Entree',
    price: 28,
    description: 'Traditional Roman pasta with guanciale, eggs, pecorino',
    thumbnail_url: '/dishes/carbonara.jpg',
    feature_count: 4,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-11',
    restaurant_id: 'rest-6',
    name: 'Tomahawk Ribeye',
    slug: 'tomahawk-ribeye',
    category: 'Entree',
    price: 65,
    description: 'Premium ribeye steak, perfectly seared, finished with butter and herbs',
    thumbnail_url: '/dishes/tomahawk-ribeye.jpg',
    feature_count: 10,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Chino Bandido
  {
    id: 'dish-12',
    restaurant_id: 'rest-7',
    name: 'Kung Pao Burrito',
    slug: 'kung-pao-burrito',
    category: 'Entree',
    price: 13,
    description: 'Asian-Mexican fusion with kung pao chicken, rice, black beans',
    thumbnail_url: '/dishes/kung-pao-burrito.jpg',
    feature_count: 6,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-13',
    restaurant_id: 'rest-7',
    name: 'Vietnamese Banh Mi Burrito',
    slug: 'banh-mi-burrito',
    category: 'Entree',
    price: 12,
    description: 'Pickled veggies, pâté, crispy exterior, fresh cilantro',
    thumbnail_url: '/dishes/banh-mi-burrito.jpg',
    feature_count: 7,
    created_at: '2024-01-01T00:00:00Z',
  },
  // The Mission
  {
    id: 'dish-14',
    restaurant_id: 'rest-8',
    name: 'Street Tacos',
    slug: 'street-tacos',
    category: 'Entree',
    price: 12,
    description: 'Fresh corn tortillas with grilled meat, salsa, onions, cilantro',
    thumbnail_url: '/dishes/street-tacos.jpg',
    feature_count: 5,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-15',
    restaurant_id: 'rest-8',
    name: 'Mission Margarita',
    slug: 'mission-margarita',
    category: 'Drink',
    price: 14,
    description: 'Fresh lime, agave, premium tequila, served on rocks',
    thumbnail_url: '/dishes/margarita.jpg',
    feature_count: 3,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Aunt Chilada's
  {
    id: 'dish-16',
    restaurant_id: 'rest-9',
    name: 'Enchiladas Rojo',
    slug: 'enchiladas-rojo',
    category: 'Entree',
    price: 15,
    description: 'Three enchiladas smothered in red sauce, cheese, served with rice and beans',
    thumbnail_url: '/dishes/enchiladas-rojo.jpg',
    feature_count: 7,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-17',
    restaurant_id: 'rest-9',
    name: 'Green Chile',
    slug: 'green-chile',
    category: 'Entree',
    price: 14,
    description: 'Famous green chile with pork, served with flour tortillas',
    thumbnail_url: '/dishes/green-chile.jpg',
    feature_count: 8,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Farm & Craft
  {
    id: 'dish-18',
    restaurant_id: 'rest-10',
    name: 'Seasonal Salad',
    slug: 'seasonal-salad',
    category: 'Entree',
    price: 16,
    description: 'Heirloom tomatoes, fresh greens, house made dressing',
    thumbnail_url: '/dishes/seasonal-salad.jpg',
    feature_count: 6,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-19',
    restaurant_id: 'rest-10',
    name: 'Grilled Vegetables',
    slug: 'grilled-vegetables',
    category: 'Entree',
    price: 14,
    description: 'Seasonal vegetables, char-grilled, olive oil finish',
    thumbnail_url: '/dishes/grilled-vegetables.jpg',
    feature_count: 4,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Dick's Hideaway
  {
    id: 'dish-20',
    restaurant_id: 'rest-11',
    name: 'Nachos',
    slug: 'nachos',
    category: 'Appetizer',
    price: 12,
    description: 'Crispy chips, cheese, jalapeños, sour cream, guacamole',
    thumbnail_url: '/dishes/nachos.jpg',
    feature_count: 5,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-21',
    restaurant_id: 'rest-11',
    name: 'Espresso Martini',
    slug: 'espresso-martini',
    category: 'Drink',
    price: 12,
    description: 'Vodka, coffee liqueur, fresh espresso, smooth and strong',
    thumbnail_url: '/dishes/espresso-martini.jpg',
    feature_count: 2,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Pane Bianco
  {
    id: 'dish-22',
    restaurant_id: 'rest-12',
    name: 'Mortadella Sandwich',
    slug: 'mortadella-sandwich',
    category: 'Entree',
    price: 8,
    description: 'House-cured mortadella, provolone, roasted peppers',
    thumbnail_url: '/dishes/mortadella-sandwich.jpg',
    feature_count: 8,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-23',
    restaurant_id: 'rest-12',
    name: 'Rosemary Focaccia',
    slug: 'rosemary-focaccia',
    category: 'Appetizer',
    price: 5,
    description: 'Soft focaccia with sea salt and fresh rosemary',
    thumbnail_url: '/dishes/rosemary-focaccia.jpg',
    feature_count: 3,
    created_at: '2024-01-01T00:00:00Z',
  },
  // SumoMaya
  {
    id: 'dish-24',
    restaurant_id: 'rest-13',
    name: 'Tuna Tataki',
    slug: 'tuna-tataki',
    category: 'Appetizer',
    price: 18,
    description: 'Seared tuna, ponzu sauce, sesame seeds, elegant plating',
    thumbnail_url: '/dishes/tuna-tataki.jpg',
    feature_count: 7,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-25',
    restaurant_id: 'rest-13',
    name: 'Omakase Set',
    slug: 'omakase-set',
    category: 'Entree',
    price: 85,
    description: 'Chef\'s selection of premium nigiri and sashimi',
    thumbnail_url: '/dishes/omakase-set.jpg',
    feature_count: 12,
    created_at: '2024-01-01T00:00:00Z',
  },
  // The Montauk
  {
    id: 'dish-26',
    restaurant_id: 'rest-14',
    name: 'Oyster Platter',
    slug: 'oyster-platter',
    category: 'Appetizer',
    price: 24,
    description: 'Fresh oysters, selection of 6 varieties with mignonette',
    thumbnail_url: '/dishes/oyster-platter.jpg',
    feature_count: 6,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-27',
    restaurant_id: 'rest-14',
    name: 'Whole Roasted Fish',
    slug: 'whole-roasted-fish',
    category: 'Entree',
    price: 55,
    description: 'Whole seasonal fish, roasted with herbs and lemon',
    thumbnail_url: '/dishes/whole-roasted-fish.jpg',
    feature_count: 8,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Little Miss BBQ
  {
    id: 'dish-28',
    restaurant_id: 'rest-15',
    name: 'Pulled Pork',
    slug: 'pulled-pork',
    category: 'Entree',
    price: 15,
    description: 'Slow smoked pork, melt-in-your-mouth tender, house sauce',
    thumbnail_url: '/dishes/pulled-pork.jpg',
    feature_count: 9,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-29',
    restaurant_id: 'rest-15',
    name: 'Texas Brisket',
    slug: 'texas-brisket',
    category: 'Entree',
    price: 18,
    description: 'Smoked brisket with crispy bark, smoky and tender',
    thumbnail_url: '/dishes/texas-brisket.jpg',
    feature_count: 10,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-30',
    restaurant_id: 'rest-15',
    name: 'BBQ Ribs',
    slug: 'bbq-ribs',
    category: 'Entree',
    price: 16,
    description: 'Slow-smoked ribs, fall off the bone, glazed with house sauce',
    thumbnail_url: '/dishes/bbq-ribs.jpg',
    feature_count: 8,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Binkley's
  {
    id: 'dish-31',
    restaurant_id: 'rest-3',
    name: '20-Course Tasting Menu',
    slug: 'tasting-menu',
    category: 'Entree',
    price: 275,
    description: 'Chef\'s 20-course culinary experience, wine pairings available',
    thumbnail_url: '/dishes/tasting-menu.jpg',
    feature_count: 15,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-32',
    restaurant_id: 'rest-3',
    name: 'Duck Breast',
    slug: 'duck-breast',
    category: 'Entree',
    price: 48,
    description: 'Pan-seared duck breast with seasonal vegetables',
    thumbnail_url: '/dishes/duck-breast.jpg',
    feature_count: 7,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Additional dishes
  {
    id: 'dish-33',
    restaurant_id: 'rest-6',
    name: 'Pasta Amatriciana',
    slug: 'pasta-amatriciana',
    category: 'Entree',
    price: 26,
    description: 'Guanciale, pecorino, tomatoes, traditional Roman preparation',
    thumbnail_url: '/dishes/amatriciana.jpg',
    feature_count: 5,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-34',
    restaurant_id: 'rest-5',
    name: 'Avocado Toast',
    slug: 'avocado-toast',
    category: 'Entree',
    price: 11,
    description: 'Sourdough toast, avocado, poached egg, everything seasoning',
    thumbnail_url: '/dishes/avocado-toast.jpg',
    feature_count: 4,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-35',
    restaurant_id: 'rest-4',
    name: 'Edamame',
    slug: 'edamame',
    category: 'Appetizer',
    price: 5,
    description: 'Steamed soybeans, sea salt',
    thumbnail_url: '/dishes/edamame.jpg',
    feature_count: 1,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-36',
    restaurant_id: 'rest-8',
    name: 'Guacamole with Chips',
    slug: 'guacamole-chips',
    category: 'Appetizer',
    price: 8,
    description: 'House-made guacamole, warm tortilla chips',
    thumbnail_url: '/dishes/guacamole.jpg',
    feature_count: 2,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-37',
    restaurant_id: 'rest-1',
    name: 'Carne Asada Tacos',
    slug: 'carne-asada-tacos',
    category: 'Entree',
    price: 14,
    description: 'Grilled marinated beef, corn tortillas, onions, cilantro',
    thumbnail_url: '/dishes/carne-asada-tacos.jpg',
    feature_count: 5,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-38',
    restaurant_id: 'rest-2',
    name: 'Diavola Pizza',
    slug: 'diavola-pizza',
    category: 'Entree',
    price: 20,
    description: 'Spicy salami, fresh mozzarella, tomato sauce, arugula',
    thumbnail_url: '/dishes/diavola-pizza.jpg',
    feature_count: 4,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-39',
    restaurant_id: 'rest-10',
    name: 'Mediterranean Bowl',
    slug: 'mediterranean-bowl',
    category: 'Entree',
    price: 17,
    description: 'Quinoa, chickpeas, cucumber, tomato, feta, tahini dressing',
    thumbnail_url: '/dishes/mediterranean-bowl.jpg',
    feature_count: 5,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dish-40',
    restaurant_id: 'rest-15',
    name: 'Mac and Cheese',
    slug: 'mac-and-cheese',
    category: 'Entree',
    price: 9,
    description: 'Creamy mac and cheese, crispy top',
    thumbnail_url: '/dishes/mac-cheese.jpg',
    feature_count: 3,
    created_at: '2024-01-01T00:00:00Z',
  },
];

// CONTENT WITH RELATIONS - combining content with creator and restaurant data
export const SEED_CONTENT_WITH_RELATIONS: ContentWithRelations[] = SEED_CONTENT.map(
  (content) => {
    const creator = SEED_CREATORS.find((c) => c.id === content.creator_id)!;
    const restaurant = SEED_RESTAURANTS.find((r) => r.id === content.restaurant_id)!;
    return {
      ...content,
      creator,
      restaurant,
    };
  }
);
